### ISSUE TITLE
Substitution is invalid error PSX - CUE to CHD.bat

### ISSUE THREAD

**Issue by jeffrey-scannell** [grioghar/retro-tools#3]
Hello, I'm getting the error below when trying to run PSX - CUE to CHD.bat. I ran RT-Retrieve-Tools first and downloaded the tools to my desktop. I have PSX - CUE to CHD.bat, config.bat, and a .7z BIN/CUE rom on the desktop as well. The only thing I changed was `set rpipsx=C:\Users\User\Desktop\psx` in config.bat.

`C:\Users\User\Desktop>"PSX - CUE to CHD.bat"`
`The following usage of the path operator in batch-parameter`
`substitution is invalid: %~nz.cue" -o "%rompath:"=%\%%~nz.chd" --force`
``
``
`For valid formats type CALL /? or FOR /?`
`The syntax of the command is incorrect.`

I was using my desktop path just to test things out, but I get the same error if I leave everything default. 

Thank you very much for sharing these scripts!

**Comment by grioghar** [comment]
ninjachamp,

First, thanks for downloading my software. This is my first attempt at a github, so it's weird for me.

I have not narrowed how to use the software yet, and that's my fault

you should the bat file with the directory of the files you're looking to compress, so:

C:\"PSX - CUE to CHD.bat" "C:\folder\of\all\of\your\store PSX files\"

I have not worked out the exclamation point bug. Any files with an exclamation point in the name will be skipped over. 

Let me know if this works for you.

**Comment by jeffrey-scannell** [comment]
Ah I was way over complicating this. It never dawned on me to pass the psx directory as a parameter. Works great when I run it the right way!

I found your reply in a reddit thread and saved it while researching chdman/psx game conversion. Most people were sharing one liners but your tools automate more and was exactly what I was looking for. Good job and thanks for sharing!

**Comment by grioghar** [comment]
Heads up @jeffrey-scannell @ninjachamp — there's a fresh round of updates to the repo in #7.

Most notably, the tool-download bootstrapper (`RT-Retrieve-Tools.bat`) is working again: several download sources had rotted (Zeranoe shut down, old 7-Zip/MAME/wget), so a fresh clone couldn't fetch ffmpeg/chdman anymore. Those URLs are refreshed.

On the converter side, `PSX-CUE-to-CHD.bat` and the others got a few fixes: quoted paths (space-safe), source ROMs are no longer deleted unless the `.chd` copy is verified, and a typo that fully broke the Dreamcast converter is fixed.

One honest caveat for this thread specifically: the **`!` (exclamation point) in filenames** bug isn't resolved yet — that's a batch delayed-expansion limitation. It's on the list for a future PowerShell port, which would clear it for good. For now, renaming affected files to drop the `!` is still the workaround.

Thanks again for the kind words and the bug report way back — much appreciated.
